### ISSUE TITLE
ConditionPathExists improvements

### ISSUE THREAD

**Issue by tzz** [brontolinux/cfengine-systemd#2]
Currently the path condition for all the units is:

```
ConditionPathExists=/var/cfengine/inputs/promises.cf
```

Would it make sense to instead depend on the configuration file for each daemon? None of them actually depend on `/var/cfengine/inputs/promises.cf`, I think.

For instance, `cf-execd` depends only on `$(sys.inputdir)/controls/cf_execd.cf`.

**Comment by brontolinux** [comment]
Can you please double check that?

I may be wrong, but I believe that **all** CFEngine daemons depend on `promises.cf` and parse it. In fact, you'll see that `cf_serverd.cf` uses variables from `bundle common def` but doesn't source it. In fact, all the bundles that are now in `control/` were earlier in `promises.cf` directly.

**Comment by tzz** [comment]
@brontolinux you're 100% right. Thanks for setting me straight :)
